### ISSUE TITLE
Deploy Link In Description Is Broken

### ISSUE THREAD

**Issue by AdebayoIbrahim** [hngx-org/zuriportfolio-frontend#354]
The Deploy URL Shown in the Description Leads to NOT FOUND Page
![Screenshot 2023-10-09 070739](https://github.com/hngx-org/zuriportfolio-frontend/assets/98415538/e283a9ac-1ce0-48c9-a579-cf568b373270)

This Should be changed to  -- (https://zuriportfolio-frontend-pw1h.vercel.app/)

**Comment by Supremacy00** [comment]
Ok
